[package]
name = "cuby"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.92"
dotenvy = "0.15.7"
rustls = { version = "0.23.43", features = ["aws_lc_rs"] }

# Async
tokio = { version = "1.53.1", features = ["full"] }
futures-util = "0.3"

# Logging
tracing = "0.1.44"
tracing-subscriber = "0.3.23"

# Twilight
twilight-cache-inmemory = "0.17.1"
twilight-gateway = "0.17.1"
twilight-http = "0.17.1"
twilight-mention = "0.17.0"
twilight-model = "0.17.1"
twilight-util = { version = "0.17.0", features = ["builder"] }

# Petpet
image = "0.25.10"
petpet-rs = { git = "https://github.com/CoreBytee/PetPet-API.git", rev = "353fb34348b6c73c46a5eae8796da498a9ae8619", version = "0.1.0" }
reqwest = "0.13.4"

# Ollama
ollama-rs = { version = "0.3.6", features = ["headers", "stream", "macros"] }

# Serde
serde = "1.0.229"
serde_json = "1.0.151"

# Time
chrono = "0.4"

# Database
rusqlite = "0.40.2"
